create table public.exercises (
  created_at timestamp with time zone not null default now(),
  name text null,
  reps numeric not null,
  weight numeric not null,
  notes text null,
  category text not null,
  rating smallint null,
  id uuid not null default gen_random_uuid (),
  date timestamp with time zone null,
  workout bigint null,
  user_id uuid null,
  image_path text null,
  myorep boolean null default false,
  dropset boolean null default false,
  constraint exercises_pk primary key (id),
  constraint exercises_workout_fkey foreign KEY (workout) references workouts (id) on delete set null
) TABLESPACE pg_default;

alter table exercises 
add column restpause boolean null default false;

alter table exercises 
add column video_path text null;

ALTER table exercises
add column volume numeric null generated always as (reps * weight) stored


create table public.workouts (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  ended_at timestamp with time zone null,
  categories text[] not null,
  is_active boolean not null default false,
  user_id uuid null,
  constraint workouts_pkey primary key (id)
) TABLESPACE pg_default;


create view categories as
    select distinct(category)
    FROM exercises ;
GRANT SELECT ON TABLE categories TO PUBLIC;


create view progression_reps as
SELECT category, name, weight, reps, date
    FROM ( 
      SELECT
        id,
        category,
        name, 
        weight, 
        reps,
        to_char(date, 'mm/DD/YYYY') as date,
        ROW_NUMBER() OVER (
            PARTITION BY name
            ORDER BY reps desc
            )
        AS rn 
          from
            exercises
          order by reps desc
    ) AS subquery where rn = 1;
GRANT SELECT ON TABLE progression_reps TO PUBLIC;

create view progression_max as
    SELECT category, name, weight, reps, date
    FROM ( 
      SELECT
        category,
        name, 
        weight, 
        reps,
        to_char(date, 'mm/DD/YYYY') as date,
        ROW_NUMBER() OVER (
            PARTITION BY name
            ORDER BY weight desc
            )
        AS rn 
          from
            exercises
    ) AS subquery where rn = 1;
GRANT SELECT ON TABLE progression_max TO PUBLIC;

create table public.exercises_canonical (
  id uuid not null default gen_random_uuid (),
  name text not null,
  category text null,
  constraint exercises_canonical_pkey primary key (id)
) TABLESPACE pg_default;

create or replace view progression_max as
    SELECT category, name, weight, reps, date
    FROM ( 
      SELECT
        category,
        name, 
        weight, 
        reps,
        volume,
        to_char(date, 'mm/DD/YYYY') as date,
        ROW_NUMBER() OVER (
            PARTITION BY name
            ORDER BY weight desc
            )
        AS rn 
          from
            exercises
    ) AS subquery where rn = 1;
    

CREATE or REPLACE VIEW exercise_options AS
select distinct name, category
from exercises
UNION 
(
  select name, category from exercises_canonical
)

GRANT SELECT ON TABLE exercise_options TO PUBLIC;


CREATE OR REPLACE view exercise_usage as
  SELECT
   COUNT(DISTINCT workout) AS total, name, category
  FROM
    exercises
  GROUP BY
  name, category
  ORDER BY
    total desc, name DESC
GRANT SELECT ON TABLE exercise_usage TO PUBLIC;      